
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "gcr/gcr-certificate-chain.h" */
#ifndef GCR_TYPE_CERTIFICATE_CHAIN_STATUS
GType gcr_certificate_chain_status_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_CERTIFICATE_CHAIN_STATUS (gcr_certificate_chain_status_get_type ())
#endif
#ifndef GCR_TYPE_CERTIFICATE_CHAIN_FLAGS
GType gcr_certificate_chain_flags_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_CERTIFICATE_CHAIN_FLAGS (gcr_certificate_chain_flags_get_type ())
#endif

/* enumerations from "gcr/gcr-certificate-request.h" */
#ifndef GCR_TYPE_CERTIFICATE_REQUEST_FORMAT
GType gcr_certificate_request_format_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_CERTIFICATE_REQUEST_FORMAT (gcr_certificate_request_format_get_type ())
#endif

/* enumerations from "gcr/gcr-column.h" */
#ifndef GCR_TYPE_COLUMN_FLAGS
GType gcr_column_flags_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_COLUMN_FLAGS (gcr_column_flags_get_type ())
#endif

/* enumerations from "gcr/gcr-deprecated-base.h" */
#ifndef GCR_TYPE_IMPORTER_PROMPT_BEHAVIOR
GType gcr_importer_prompt_behavior_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_IMPORTER_PROMPT_BEHAVIOR (gcr_importer_prompt_behavior_get_type ())
#endif

/* enumerations from "gcr/gcr-prompt.h" */
#ifndef GCR_TYPE_PROMPT_REPLY
GType gcr_prompt_reply_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_PROMPT_REPLY (gcr_prompt_reply_get_type ())
#endif

/* enumerations from "gcr/gcr-system-prompt.h" */
#ifndef GCR_TYPE_SYSTEM_PROMPT_ERROR
GType gcr_system_prompt_error_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_SYSTEM_PROMPT_ERROR (gcr_system_prompt_error_get_type ())
#endif

/* enumerations from "gcr/gcr-system-prompter.h" */
#ifndef GCR_TYPE_SYSTEM_PROMPTER_MODE
GType gcr_system_prompter_mode_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_SYSTEM_PROMPTER_MODE (gcr_system_prompter_mode_get_type ())
#endif

/* enumerations from "gcr/gcr-types.h" */
#ifndef GCR_TYPE_DATA_ERROR
GType gcr_data_error_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_DATA_ERROR (gcr_data_error_get_type ())
#endif
#ifndef GCR_TYPE_DATA_FORMAT
GType gcr_data_format_get_type (void) G_GNUC_CONST;
#define GCR_TYPE_DATA_FORMAT (gcr_data_format_get_type ())
#endif
G_END_DECLS

/* Generated data ends here */

