#!/sbin/openrc-run
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

command="/usr/bin/universalmediaserver"
command_args="console"
pidfile="${PMS_PIDFILE:-/var/run/ums.pid}"
retry="10"
start_stop_daemon_args="
	--background
	--make-pidfile
	${UMS_USER:+--user} ${UMS_USER}
	${UMS_GROUP:+--group} ${UMS_GROUP}
"

depend() {
	need net
}
