// Generated by gmmproc 2.60.0 -- DO NOT MODIFY!
#ifndef _GTKMM_RADIOACTION_P_H
#define _GTKMM_RADIOACTION_P_H
#ifndef GTKMM_DISABLE_DEPRECATED


#include <gtkmm/private/toggleaction_p.h>

#include <glibmm/class.h>

namespace Gtk
{

class RadioAction_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  using CppObjectType = RadioAction;
  using BaseObjectType = GtkRadioAction;
  using BaseClassType = GtkRadioActionClass;
  using CppClassParent = Gtk::ToggleAction_Class;
  using BaseClassParent = GtkToggleActionClass;

  friend class RadioAction;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();


  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.
#ifndef GTKMM_DISABLE_DEPRECATED

  static void changed_callback(GtkRadioAction* self, GtkRadioAction* p0);
#endif // GTKMM_DISABLE_DEPRECATED


  //Callbacks (virtual functions):
};


} // namespace Gtk

#endif // GTKMM_DISABLE_DEPRECATED


#endif /* _GTKMM_RADIOACTION_P_H */

