// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KCODECS_VERSION_H
#define KCODECS_VERSION_H

#define KCODECS_VERSION_STRING "5.70.0"
#define KCODECS_VERSION_MAJOR 5
#define KCODECS_VERSION_MINOR 70
#define KCODECS_VERSION_PATCH 0
#define KCODECS_VERSION ((5<<16)|(70<<8)|(0))

#endif
